/** Incident report (Markdown) - port of pipeline/report.py for the hosted workspace. */
import type { Incident } from "./engine/types";
import { EVENT_TYPES } from "./engine/rules";

const v = (x: unknown, nd = 3) => (x == null ? "n/a" : typeof x === "number" ? (Number.isFinite(x) ? x.toFixed(nd) : "n/a") : String(x));

export function incidentReportMd(inc: Incident): string {
  const L: string[] = [];
  L.push(`# Incident report ${inc.id}`, "");
  L.push(`**Status:** ${inc.status}  `);
  L.push(`**Event type (hypothesis):** ${inc.event_type_hypothesis} - ${EVENT_TYPES[inc.event_type_hypothesis] || ""}  `);
  L.push(`**AOI:** ${inc.aoi_name || inc.aoi_id}  `);
  L.push(`**Observation:** ${inc.observation_time}  `, `**Detected:** ${inc.detected_at}  `, `**Raised by model:** ${inc.model_id}  `);
  L.push(`**Severity / confidence:** ${v(inc.severity, 2)} / ${v(inc.confidence, 2)} (reported separately, never multiplied)  `);
  if (inc.disposition) L.push(`**Disposition:** ${inc.disposition}  `);
  L.push("", "> Optical satellite evidence identifies an anomaly in how the water scatters and absorbs light. It does not identify a species, a toxin or a substance. Field sampling and laboratory analysis confirm.", "");
  const rec = inc.recommendation;
  if (rec) {
    L.push("## Recommended action", `**${rec.action}** (priority ${rec.priority})`);
    rec.reasons.forEach((r) => L.push(`- ${r}`));
    if (rec.required_evidence.length) { L.push("", "Required evidence:"); rec.required_evidence.forEach((r) => L.push(`- ${r}`)); }
    if (rec.decision_deadline_utc) L.push("", `Decision deadline: ${rec.decision_deadline_utc}`);
    L.push("");
  }
  L.push("## Evidence", "### Temporal context");
  L.push(`- Seasonal percentile of the primary indicator: ${v(inc.temporal?.seasonal_percentile, 1)} (n = ${inc.temporal?.n_seasonal ?? "n/a"})`);
  const feats = { ...(inc.water_quality?.estimates || {}), ...(inc.water_quality?.features || {}) };
  if (Object.keys(feats).length) {
    L.push("### Water-quality indicators", "| Indicator | Value | Units | Kind | Seasonal pct |", "|---|---|---|---|---|");
    Object.entries(feats).forEach(([k, e]) => L.push(`| ${e.label || k} | ${v(e.value)} | ${e.units || ""} | ${e.quantity_kind} | ${v(e.seasonal_percentile, 0)} |`));
  }
  const ag = inc.sensor_agreement || {};
  if (Object.keys(ag).length) {
    L.push("### Cross-sensor evidence");
    Object.entries(ag).forEach(([k, a]) => L.push(`- ${k}: ${a.agrees ? "agrees" : a.agrees === false ? "does not agree" : "not available"}${a.note ? ` - ${a.note}` : ""}`));
  }
  if (inc.quality_flags?.length) { L.push("### Quality flags"); inc.quality_flags.forEach((q) => L.push(`- ${q}`)); }
  if (inc.reviews?.length) {
    L.push("", "## Operator reviews", "| When | Reviewer | Decision | From -> to | Note |", "|---|---|---|---|---|");
    inc.reviews.forEach((r) => L.push(`| ${r.created_at} | ${r.reviewer} | ${r.decision}${r.new_hypothesis ? ` -> ${r.new_hypothesis}` : ""} | ${r.status_before} -> ${r.status_after} | ${(r.note || "").replace(/\|/g, "/")} |`));
  }
  if (inc.samples?.length) {
    L.push("", "## Field sampling plan", "| Code | Role | Lat | Lon | Status |", "|---|---|---|---|---|");
    inc.samples.forEach((s) => L.push(`| ${s.code} | ${s.role} | ${s.lat.toFixed(5)} | ${s.lon.toFixed(5)} | ${s.status} |`));
  }
  if (inc.measurements?.length) {
    L.push("", "## Field and laboratory measurements", "| Parameter | Value | Unit | Sample | Method | QC | Entered by |", "|---|---|---|---|---|---|---|");
    inc.measurements.forEach((m) => L.push(`| ${m.parameter} | ${m.value} | ${m.unit} | ${m.sample_id || ""} | ${m.method || ""} | ${m.qc_flag} | ${m.entered_by} |`));
  }
  if (inc.provenance?.sources?.length) {
    L.push("", "## Provenance", "| Sensor | Scene | Acquired | Level | Provider | Licence |", "|---|---|---|---|---|---|");
    inc.provenance.sources.forEach((s) => L.push(`| ${s.sensor || s.satellite || ""} | ${s.scene_id || ""} | ${s.acquisition_utc || ""} | ${s.processing_level || ""} | ${s.provider || ""} | ${s.licence || ""} |`));
  }
  if (inc.audit_trail?.length) {
    L.push("", "## Audit trail (hash-chained)", "| Seq | When | Actor | Action | Hash |", "|---|---|---|---|---|");
    [...inc.audit_trail].sort((a, b) => a.seq - b.seq).forEach((a) => L.push(`| ${a.seq} | ${a.at} | ${a.actor} | ${a.action} | \`${a.hash.slice(0, 16)}\` |`));
  }
  L.push("", "_Generated by BLUEBAN 813. Built by Team Kanban._");
  return L.join("\n");
}

export function download(name: string, text: string, type = "text/markdown") {
  const blob = new Blob([text], { type });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = name;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 500);
}
